---
- name: Install packages
  ansible.builtin.package:
    name:
      - rhc-worker-playbook
      - yara
      - scap-security-guide
      - postgresql-server
    state: present

- name: Initialize the db
  ansible.builtin.command: >-
    /usr/bin/postgresql-setup --initdb

- name: Enable and start the postgresql service
  ansible.builtin.service:
    name: postgresql
    enabled: true
    state: started

- name: Register node with Red Hat Insights
  ansible.builtin.command: >-
    rhc connect
    -o {{ lb1152_hol_node_config_insights_org }}
    -a {{ lb1152_hol_node_config_insights_activation_key }}

- name: Run insights-client to generate config files
  ansible.builtin.command: insights-client --collector malware-detection

- name: Configure insight malware detection - 1
  ansible.builtin.lineinfile:
    line: "test_scan: false"
    regexp: "^test_scan: true"
    path: /etc/insights-client/malware-detection-config.yml
