---
- name: Reset satellite admin password
  when: lb1152_hol_satellite_reconfigure_reset_password | bool
  block:
    - name: Reset satellite admin password
      ansible.builtin.command: "foreman-rake permissions:reset password={{ lb1152_hol_satellite_reconfigure_user_password }}"

    - name: Update hammer cli config password
      ansible.builtin.lineinfile:
        path: /root/.hammer/cli.modules.d/foreman.yml
        regexp: 'password'
        line: "  :password: '{{ lb1152_hol_satellite_reconfigure_user_password }}'"

- name: Update Satellite hostname
  when: lb1152_hol_satellite_reconfigure_update_hostname | bool
  block:
    - name: Remove old satelite entry from /etc/hosts
      ansible.builtin.lineinfile:
        dest: /etc/hosts
        regexp: '.*satellite.example.com'
        state: absent

    - name: Gather host ip address
      ansible.builtin.set_fact:
        host_ip: "{{ ansible_default_ipv4.address }}"

    - name: Update hostname in /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ host_ip }} {{ lb1152_hol_satellite_reconfigure_internal_fqdn }}"
        state: present
        create: true

    - name: Update hostname using hostnamectl
      ansible.builtin.command: >-
        hostnamectl set-hostname {{ lb1152_hol_satellite_reconfigure_internal_fqdn }}

    - name: Update satellite hostname 
      ansible.builtin.shell: >-
        satellite-change-hostname {{ lb1152_hol_satellite_reconfigure_external_fqdn }}
        -u {{ lb1152_hol_satellite_reconfigure_user_name }} -p {{ lb1152_hol_satellite_reconfigure_user_password }} --skip-dns --assumeyes
      register: satellite_change_hostname
      failed_when: '"Success!" not in satellite_change_hostname.stdout'

- name: Replace satellite anifest
  when: lb1152_hol_satellite_reconfigure_replace_manifest | bool
  block:
    - name: Refresh the manifest
      ansible.builtin.command: 'hammer subscription refresh-manifest --organization="Default Organization"'
