---
- name: Copy SSH files
  ansible.builtin.copy:
    src: "/home/{{ lb1152_hol_satellite_reconfigure_lab_user }}/.ssh/{{ item }}"
    dest: /root/.ssh/
    remote_src: true
    owner: root
    group: root
  loop:
    - authorized_keys
    - "{{ guid }}key.pub"
    - config

- name: Copy private ssh key
  ansible.builtin.copy:
    src: "/home/{{ lb1152_hol_satellite_reconfigure_lab_user }}/.ssh/{{ guid }}key.pem"
    dest: /root/.ssh/
    remote_src: true
    owner: root
    group: root
    mode: 0400

- name: Add root user in config
  ansible.builtin.lineinfile:
    regexp: ".*User ec2-user$"
    line: "  User root"
    path: /root/.ssh/config
