---
# ----------------------------------------------------------------
# User's Variables
# ----------------------------------------------------------------
lb1152_hol_satellite_reconfigure_lab_user: "{{ student_name }}"

# ----------------------------------------------------------------
# Default Variables
# ----------------------------------------------------------------
lb1152_hol_satellite_reconfigure_external_fqdn: "{{ groups['satellites'][0].split('.')[0] }}.{{ subdomain_base }}"
lb1152_hol_satellite_reconfigure_internal_fqdn: satellite.example.com
lb1152_hol_satellite_reconfigure_user_name: admin
lb1152_hol_satellite_reconfigure_user_password: <CHANGEME>

# ----------------------------------------------------------------
# Register satellite with RHSM
# ----------------------------------------------------------------
lb1152_hol_satellite_reconfigure_subscription_type: rhsm
lb1152_hol_satellite_reconfigure_sat_org: "{{ lb1152_hol_node_config_sat_org }}"
lb1152_hol_satellite_reconfigure_sat_activation_key: "{{ lb1152_hol_node_config_sat_activation_key }}"
lb1152_hol_satellite_reconfigure_insights_org: "{{ lb1152_hol_node_config_insights_org }}"
lb1152_hol_satellite_reconfigure_insights_activation_key: "{{ lb1152_hol_node_config_insights_activation_key }}"

# ----------------------------------------------------------------
# iop Variables
# ----------------------------------------------------------------
lb1152_hol_satellite_reconfigure_iop_image_path: <CHANGEME>
lb1152_hol_satellite_reconfigure_iop_image_stage_url: <CHANGEME>
lb1152_hol_satellite_reconfigure_iop_image_id_rm: <CHANGEME>
lb1152_hol_satellite_reconfigure_iop_image_url: <CHANGEME>
